### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by mdzh10** [mjkvaak/ImageDataAugmentor#21] opened 2023-04-03 20:17 UTC
I have a data generator for image segmentation. Here is the code below:
```python
AUGMENTATIONS = A.Compose([
    A.Transpose(p=0.5),
    A.Flip(p=0.5),
    A.OneOf([
        A.RandomBrightnessContrast(brightness_limit=0.3, contrast_limit=0.3),
        A.RandomBrightnessContrast(brightness_limit=0.1, contrast_limit=0.1)
    ],p=1),
    A.GaussianBlur(p=0.05),
    A.HueSaturationValue(p=0.5),
    A.RGBShift(p=0.5),
])
 
N_CLASSES = 1 # number of segmentation classes in masks

def one_hot_encode_masks(y:np.array, classes=range(N_CLASSES)):
    ''' One hot encodes target masks for segmentation '''
    y = y.squeeze()
    masks = [(y == v) for v in classes]
    mask = np.stack(masks, axis=-1).astype('float')
    # add background if the mask is not binary
    if mask.shape[-1] != 1:
        background = 1 - mask.sum(axis=-1, keepdims=True)
        mask = np.concatenate((mask, background), axis=-1)
    return mask

img_data_gen = ImageDataAugmentor(
    augment=AUGMENTATIONS, 
    input_augment_mode='image', 
    seed=seed_,
)
mask_data_gen = ImageDataAugmentor(
    augment=AUGMENTATIONS, 
    input_augment_mode='mask', #<- notice the different augment mode
    # preprocess_input=one_hot_encode_masks,
    seed=seed_,
)
print("training:")
tr_img_gen = img_data_gen.flow_from_directory(source_path,
                                              target_size = (img_dims[0],img_dims[1]), 
                                              classes = [folders[0]], 
                                              class_mode=None,
                                              batch_size = batch_,
                                            #   subset="training", 
                                              shuffle=True)
tr_mask_gen = mask_data_gen.flow_from_directory(source_path, 
                                                target_size = (img_dims[0],img_dims[1]),
                                                classes = [folders[2]],
                                                class_mode=None, 
                                                batch_size = batch_,
                                                color_mode='gray', #<- notice the color mode
                                                # subset="training",
                                                shuffle=True)
print("validation:")
val_img_gen = img_data_gen.flow_from_directory(source_path_val, 
                                               target_size = (img_dims[0],img_dims[1]),
                                               classes = [folders[0]],
                                               class_mode=None,
                                               batch_size = batch_,
                                            #    subset="validation", 
                                               shuffle=True)
val_mask_gen = mask_data_gen.flow_from_directory(source_path_val, 
                                                 target_size = (img_dims[0],img_dims[1]),
                                                 classes = [folders[2]], 
                                                 class_mode=None,
                                                 batch_size = batch_, 
                                                 color_mode='gray', #<- notice the color mode
                                                #  subset="validation",
                                                 shuffle=True)
#tr_img_gen.show_data()
#tr_mask_gen.show_data()

train_generator = zip(tr_img_gen, tr_mask_gen)
validation_generator = zip(tr_img_gen, tr_mask_gen)

# visualize images
rows = 5
image_batch, mask_batch = next(train_generator)
fix, ax = plt.subplots(rows,2, figsize=(4,rows*2))
for i, (img,mask) in enumerate(zip(image_batch, mask_batch)):
    if i>rows-1:
        break
    ax[i,0].imshow(np.uint8(img))
    ax[i,1].imshow(mask.argmax(-1))
    
plt.show()
```
After calling the generator it raises error "ValueError: setting an array element with a sequence." Can u plz help @mjkvaak ?

**Comment by mjkvaak** [comment] 2023-04-13 06:08
I couldn't reproduce your error. Maybe it has something to do with your data? I did

```python
import os
import matplotlib.pyplot as plt
from ImageDataAugmentor.image_data_augmentor import *
import albumentations as A

source_path = './data/CamVid/'

# clone the repository with dataset if it does not exists
if not os.path.exists(source_path):
    print('Loading data...', end=" ")
    os.system('git clone https://github.com/alexgkendall/SegNet-Tutorial ./data')
    print('done!')

source_path_val = source_path
img_dims = (124, 124)
folders = ["train", "dummy", "trainannot"]

AUGMENTATIONS = A.Compose([
    A.Transpose(p=0.5),
    A.Flip(p=0.5),
    A.OneOf([
        A.RandomBrightnessContrast(brightness_limit=0.3, contrast_limit=0.3),
        A.RandomBrightnessContrast(brightness_limit=0.1, contrast_limit=0.1)
    ],p=1),
    A.GaussianBlur(p=0.05),
    A.HueSaturationValue(p=0.5),
#     A.RGBShift(p=0.5),  #<- commented out because masks are binary
])

# ... rest of your code here ...
```
and it worked without any complaints. I'm therefore closing the issue. Should the problem persist, please provide me with a minimal reproducible example: "ValueError: setting an array element with a sequence." is not informative enough to understand the root cause.

**Closed as completed by mjkvaak** 2023-04-13 06:08 UTC
